site_name: Painel V2
# repo_url: 
repo_name: Painel V2
site_name: Painel

nav:
  - Home: index.md
  - Atas de reunião: 
    - Ata reunião 1: atas-reuniao/ata-reuniao1.md
  
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
    - toc.follow
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: pt-BR
  favicon: ../../site/assets/images/logo_20px.png
  logo: ../../site/assets/images/logo_200px.png
  palette:
    - scheme: default
      toggle:
        icon: material/globe-light
        name: Dark mode
      primary: grey
      accent: grey
    - scheme: slate
      toggle:
        icon: material/globe-light-outline
        name: Light mode
      primary: grey
      accent: grey

markdown_extensions:
  - attr_list

extra: 
  assets:
    - assets/images/