site_name: Painel V2
# repo_url: 
repo_name: Painel V2
site_name: Painel

nav:
  - Home: index.md
  - Meetings:
    - Model Meeting: meeting-minutes/model-meeting.md 
    - Meeting minutes 001: meeting-minutes/meeting1.md
    - Meeting minutes 002: meeting-minutes/meeting2.md
    - Meeting minutes 003: meeting-minutes/meeting3.md
    - Meeting minutes 004: meeting-minutes/meeting4.md
    - Meeting minutes 005: meeting-minutes/meeting5.md
  - Planning: 
    - Sprints: planning/sprints.md
  - Product Management: 
    - Backlog: product-management/backlog.md
    - User Stories: product-management/user-stories.md
    - RoadMap: product-management/roadmap.md
  - Requirements: 
    - Personas: requirements/personas.md
  
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
    - toc.follow
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: pt-BR
  favicon: ../assets/logo_20px.png
  logo: ../assets/images/Logo FGR branca verdelimao.png
  palette:
    - scheme: default
      toggle:
        icon: material/globe-light
        name: Dark mode
      primary: grey
      accent: grey
    - scheme: slate
      toggle:
        icon: material/globe-light-outline
        name: Light mode
      primary: grey
      accent: grey

markdown_extensions:
  - attr_list

extra: 
extra_css:
  - css/custom.css

docs_dir: docs

extra:
  assets:
    - site/assets/images/
