site_name: Painel V2

nav:
  - Home: index.md
  - Metodologia: visao-painel/metodologia.md
  - Requisitos: visao-painel/requisitos.md
  
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
    - toc.follow
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: pt

  palette:
    - scheme: default
      toggle:
        icon: material/globe-light
        name: Dark mode
      primary: green
      accent: green
    - scheme: slate
      toggle:
        icon: material/globe-light-outline
        name: Light mode
      primary: green
      accent: green

markdown_extensions:
  - attr_list

extra_css:
  - css/custom.css